/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.pkg2.pkg0;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author aliciafermano
 */
public class SummeraKostnader extends javax.swing.JFrame {
    private InfDB idb;
    private String anvandareID;

    /**
     * Creates new form SummeraKostnader
     */
    public SummeraKostnader(InfDB idb, String anvandareID) {
        initComponents();
        this.idb = idb;
        this.anvandareID=anvandareID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVisaStatistik = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtTotalKostnad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Statistik Över Projektkostnader");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnVisaStatistik.setText("Visa Statistik");
        btnVisaStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaStatistikActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisaStatistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 480, 160, 70));

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTillbaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 110, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 270, 360));

        txtTotalKostnad.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtTotalKostnad.setText("Totalkostnad");
        getContentPane().add(txtTotalKostnad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaStatistikActionPerformed
        try {
    String sqlQuery = "SELECT projekt.namn, COALESCE(SUM(kostnader.kostnad), 0) AS total_kostnad " +
                      "FROM projekt " +
                      "LEFT JOIN kostnader ON projekt.pid = kostnader.projekt_pid " +
                      "WHERE projekt.projektchef = '" + anvandareID + "' " +
                      "GROUP BY projekt.namn";

    // Variabel för totalkostnad
    double totalkostnad = 0;

    // Rensa textområden
    jTextArea1.setText("");
    txtTotalKostnad.setText("");

    // Iterera över alla rader manuellt
    HashMap<String, String> rad;
    boolean hasResults = false;

    for (int i = 1; (rad = idb.fetchRow(sqlQuery)) != null; i++) {
        hasResults = true;

        String projektNamn = rad.get("namn");
        String kostnad = rad.get("total_kostnad");

        // Lägg till data i textområdet
        jTextArea1.append("Projekt: " + projektNamn + "\n");
        jTextArea1.append("Kostnad: " + kostnad + " kr\n\n");

        // Summera totalkostnaden
        totalkostnad += Double.parseDouble(kostnad);
    }

    // Om inga resultat hittades
    if (!hasResults) {
        jTextArea1.append("Inga projekt hittades eller inga kostnader registrerade.\n");
    }

    // Visa totalkostnaden
    txtTotalKostnad.setText(totalkostnad + " kr");

} catch (InfException e) {
    JOptionPane.showMessageDialog(this, "Fel vid hämtning av statistik: " + e.getMessage(), 
                                  "Fel", JOptionPane.ERROR_MESSAGE);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Fel vid konvertering av data: " + e.getMessage(), 
                                  "Fel", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Ett oväntat fel inträffade: " + e.getMessage(), 
                                  "Fel", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnVisaStatistikActionPerformed
    private JFrame frame;
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        frame = new JFrame ("Exit");
         if(JOptionPane.showConfirmDialog(frame,"Bekräfta om du vill avsluta","Information om anställda",
                 JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
         {
             System.exit(0);
         }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummeraKostnader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummeraKostnader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummeraKostnader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummeraKostnader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SummeraKostnader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaStatistik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtTotalKostnad;
    // End of variables declaration//GEN-END:variables
}
