/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.pkg2.pkg0;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author aliciafermano
 */
public class SökProjekt extends javax.swing.JFrame {
    private InfDB idb;

    /**
     * Creates new form SökProjekt
     */
    public SökProjekt(InfDB idb) {
        initComponents();
        this.idb = idb;
    }
    
    private void sökProjekt() {
        try {
            
            String startdatum = textFieldStartDatum.getText();
            String slutDatum = textFieldSlutDatum.getText();
            
            
            if (startdatum.isEmpty()|| slutDatum.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ange både start- och slutdatum.");
                return;
            }
            
            System.out.println("SQL Query: SELECT projektnamn FROM projekt WHERE startdatum >= '" + startdatum + "' AND slutdatum <= '" + slutDatum +"'");
            String query = "SELECT projektnamn FROM projekt WHERE startDatum >= '" + startdatum + "' AND slutdatum <= '" + slutDatum + "'";
            
            List<String> projekt = idb.fetchColumn(query);
            textAreaResultat.setText("");
            
            if (projekt != null && !projekt.isEmpty()) {
                for (String namn : projekt) {
                    textAreaResultat.append(namn + "\n");
                }
            } else {
                textAreaResultat.setText("Inga projekt hittades för det angivna datumspannet.");
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av projekt" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldStartDatum = new javax.swing.JTextField();
        textFieldSlutDatum = new javax.swing.JTextField();
        sökKnapp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldStartDatum.setText("startdatum");
        getContentPane().add(textFieldStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 209, 158, 85));

        textFieldSlutDatum.setText("Slutdatum");
        getContentPane().add(textFieldSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 351, 144, 74));

        sökKnapp.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        sökKnapp.setText("Sök");
        sökKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sökKnappActionPerformed(evt);
            }
        });
        getContentPane().add(sökKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 97, 92, 46));

        textAreaResultat.setColumns(20);
        textAreaResultat.setRows(5);
        jScrollPane1.setViewportView(textAreaResultat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, -1, 302));

        jLabel1.setText("(ÅÅÅÅ-MM-DD)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 150, -1));

        jLabel2.setText("(ÅÅÅÅ-MM-DD)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sökKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sökKnappActionPerformed

        sökProjekt();
    }//GEN-LAST:event_sökKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SökProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SökProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SökProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SökProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SökProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sökKnapp;
    private javax.swing.JTextArea textAreaResultat;
    private javax.swing.JTextField textFieldSlutDatum;
    private javax.swing.JTextField textFieldStartDatum;
    // End of variables declaration//GEN-END:variables
}
