/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.pkg2.pkg0;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author aliciafermano
 */
public class ÄndraProjektProjektChef extends javax.swing.JFrame {
    private InfDB idb;
    private String anvandareID;

    /**
     * Creates new form ÄndraProjektProjektChef
     */
    public ÄndraProjektProjektChef(InfDB idb, String anvandareID) {
        initComponents();
        this.idb = idb;
        this.anvandareID=anvandareID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLand = new javax.swing.JTextField();
        txtStartdatum = new javax.swing.JTextField();
        txtStartDatum = new javax.swing.JTextField();
        txtPid = new javax.swing.JTextField();
        txtProjektNamn = new javax.swing.JTextField();
        txtProjektChef = new javax.swing.JTextField();
        txtPrioritet = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtSlutDatum = new javax.swing.JTextField();
        txtKostnad = new javax.swing.JTextField();
        btnHämtaProjekt = new javax.swing.JButton();
        btnÄndraProjekt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 359, 430));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("pid");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Projektnamn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Startdatum");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Beskrivning");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Kostnad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Slutdatum");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Projektchef");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, -1, -1));

        lblPrioritet.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPrioritet.setText("Prioritet");
        getContentPane().add(lblPrioritet, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setText("Land");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, -1));

        txtLand.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 220, -1));

        txtStartdatum.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtStartdatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 220, -1));

        txtStartDatum.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtStartDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDatumActionPerformed(evt);
            }
        });
        getContentPane().add(txtStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 220, -1));

        txtPid.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 220, -1));

        txtProjektNamn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtProjektNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 220, -1));

        txtProjektChef.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtProjektChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjektChefActionPerformed(evt);
            }
        });
        getContentPane().add(txtProjektChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 220, -1));

        txtPrioritet.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtPrioritet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrioritetActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrioritet, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 220, -1));

        txtStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 230, -1));

        txtSlutDatum.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 220, -1));

        txtKostnad.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(txtKostnad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 230, -1));

        btnHämtaProjekt.setText("Mina Projekt");
        btnHämtaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaProjektActionPerformed(evt);
            }
        });
        getContentPane().add(btnHämtaProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 140, 80));

        btnÄndraProjekt.setText("Ändra Projekt");
        btnÄndraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraProjektActionPerformed(evt);
            }
        });
        getContentPane().add(btnÄndraProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 140, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 6));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel9.setText("Ändra mina projekt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 110));

        lblExit.setText("Exit");
        lblExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblExitActionPerformed(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 70, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStartDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDatumActionPerformed

    private void txtPrioritetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrioritetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrioritetActionPerformed

    private void txtProjektChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjektChefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjektChefActionPerformed

    private void btnHämtaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaProjektActionPerformed
        // TODO add your handling code here:
        try {
        // Hämta alla projekt där användaren är projektchef
        String query = "SELECT * FROM projekt WHERE projektchef = '" + anvandareID + "'";
        List<String> projektList = idb.fetchColumn(query);

        if (projektList != null && projektList.size() > 0) {
            // Visa projekten i textområdet eller en annan komponent (exempelvis en lista)
            StringBuilder sb = new StringBuilder();
            for (String projektId : projektList) {
                sb.append(projektId).append("\n");
            }
            jTextArea1.setText(sb.toString()); // Fyll i textområdet med projekten
        } else {
            JOptionPane.showMessageDialog(this, "Inga projekt hittades.");
        }
    } catch (InfException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ett fel inträffade när projekten skulle hämtas.");
    }
    }//GEN-LAST:event_btnHämtaProjektActionPerformed

    private void btnÄndraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraProjektActionPerformed
        // TODO add your handling code here:
        
        try {
        // Uppdatera projektet med de nya värdena från textfälten
        String pid = txtPid.getText();
        String projektNamn = txtProjektNamn.getText();
        String startDatum = txtStartdatum.getText();
        String slutDatum = txtSlutDatum.getText();
        String kostnad = txtKostnad.getText();
        String prioritet = txtPrioritet.getText();
        String status = txtStatus.getText();
        String projektChef = txtProjektChef.getText();
        String land = txtLand.getText();

        // Bygg uppdateringsfrågan
        String query = "UPDATE projekt SET projektNamn = '" + projektNamn + "', " +
                       "startDatum = '" + startDatum + "', " +
                       "slutDatum = '" + slutDatum + "', " +
                       "kostnad = '" + kostnad + "', " +
                       "prioritet = '" + prioritet + "', " +
                       "status = '" + status + "', " +
                       "projektchef = '" + projektChef + "', " +
                       "land = '" + land + "' " +
                       "WHERE pid = '" + pid + "'";

        // Använd InfDB:s update-metod
        idb.update(query);

        // Bekräftelse
        JOptionPane.showMessageDialog(this, "Projektinformation har uppdaterats.");
    } catch (InfException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ett fel inträffade när projektet skulle uppdateras.");
    }
    }//GEN-LAST:event_btnÄndraProjektActionPerformed

    private void lblExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblExitActionPerformed
        int svar = JOptionPane.showConfirmDialog(this, 
        "Är du säker på att du vill gå tillbaka till menyn?", 
        "Bekräfta", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);
    
    if (svar == JOptionPane.YES_OPTION) {
        new infoOmProjekt(idb,anvandareID).setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_lblExitActionPerformed

    private void visaProjektInfo(String pid) {
    try {
        String query = "SELECT * FROM projekt WHERE pid = '" + pid + "'";
        List<String> projektInfo = idb.fetchColumn(query);

        if (projektInfo != null && projektInfo.size() > 0) {
            // Fyll i fälten med data
            txtPid.setText(projektInfo.get(0));
            txtProjektNamn.setText(projektInfo.get(1));
            txtStartdatum.setText(projektInfo.get(2));
            txtSlutDatum.setText(projektInfo.get(3));
            txtKostnad.setText(projektInfo.get(4));
            txtPrioritet.setText(projektInfo.get(5));
            txtStatus.setText(projektInfo.get(6));
            txtProjektChef.setText(projektInfo.get(7));
            txtLand.setText(projektInfo.get(8)); // Om Land finns i resultatet
        } else {
            JOptionPane.showMessageDialog(this, "Projektet hittades inte.");
        }
    } catch (InfException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ett fel inträffade när projektinformationen skulle hämtas.");
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektProjektChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektProjektChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektProjektChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektProjektChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ÄndraProjektProjektChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämtaProjekt;
    private javax.swing.JButton btnÄndraProjekt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lblExit;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JTextField txtKostnad;
    private javax.swing.JTextField txtLand;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPrioritet;
    private javax.swing.JTextField txtProjektChef;
    private javax.swing.JTextField txtProjektNamn;
    private javax.swing.JTextField txtSlutDatum;
    private javax.swing.JTextField txtStartDatum;
    private javax.swing.JTextField txtStartdatum;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
