/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.pkg2.pkg0;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author sabri
 */
public class ÄndraPartners extends javax.swing.JFrame {
    private InfDB idb;
    private String anvandareID;

    /**
     * Creates new form ÄndraPartners
     */
    public ÄndraPartners(InfDB idb, String anvandareID) {
        this.idb = idb;
        this.anvandareID = anvandareID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        lblpid = new javax.swing.JLabel();
        lblKontaktperson = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtStad = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtKontaktEpost = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtKontaktPerson = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLäggTill = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        btnÄndra = new javax.swing.JButton();
        btnÅterställ = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Information om partners");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(273, 273, 273))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        lblNamn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamn.setForeground(new java.awt.Color(0, 153, 153));
        lblNamn.setText("Namn");

        lblpid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpid.setForeground(new java.awt.Color(0, 153, 153));
        lblpid.setText("pid");

        lblKontaktperson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKontaktperson.setForeground(new java.awt.Color(0, 153, 153));
        lblKontaktperson.setText("Kontaktperson");

        lblKontaktEpost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKontaktEpost.setForeground(new java.awt.Color(0, 153, 153));
        lblKontaktEpost.setText("Konaktepost");

        lblStad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStad.setForeground(new java.awt.Color(0, 153, 153));
        lblStad.setText("Stad");

        lblTelefon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelefon.setForeground(new java.awt.Color(0, 153, 153));
        lblTelefon.setText("Telefon");

        lblAdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdress.setForeground(new java.awt.Color(0, 153, 153));
        lblAdress.setText("Adress");

        lblBranch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBranch.setForeground(new java.awt.Color(0, 153, 153));
        lblBranch.setText("Branch");

        txtpid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtpid.setForeground(new java.awt.Color(0, 153, 153));

        txtStad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtStad.setForeground(new java.awt.Color(0, 153, 153));

        txtBranch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBranch.setForeground(new java.awt.Color(0, 153, 153));

        txtAdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAdress.setForeground(new java.awt.Color(0, 153, 153));

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTelefon.setForeground(new java.awt.Color(0, 153, 153));

        txtKontaktEpost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtKontaktEpost.setForeground(new java.awt.Color(0, 153, 153));

        txtNamn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNamn.setForeground(new java.awt.Color(0, 153, 153));

        txtKontaktPerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtKontaktPerson.setForeground(new java.awt.Color(0, 153, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        btnLäggTill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLäggTill.setText("Lägg Till");
        btnLäggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillActionPerformed(evt);
            }
        });

        btnTaBort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaBort.setText("Ta Bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnÄndra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnÄndra.setText("Ändra");
        btnÄndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraActionPerformed(evt);
            }
        });

        btnÅterställ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnÅterställ.setText("Återställ");
        btnÅterställ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÅterställActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnÄndra, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnÅterställ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLäggTill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnTaBort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnLäggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnÄndra, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnÅterställ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpid)
                    .addComponent(lblStad)
                    .addComponent(lblBranch)
                    .addComponent(lblAdress)
                    .addComponent(lblTelefon)
                    .addComponent(lblKontaktEpost)
                    .addComponent(lblNamn)
                    .addComponent(lblKontaktperson))
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKontaktPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpid)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamn)
                            .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKontaktperson)
                            .addComponent(txtKontaktPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKontaktEpost)
                            .addComponent(txtKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefon)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdress)
                            .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBranch)
                            .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStad)
                            .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1030, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         int svar = JOptionPane.showConfirmDialog(this, 
        "Är du säker på att du vill gå tillbaka till menyn?", 
        "Bekräfta", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);
    
    if (svar == JOptionPane.YES_OPTION) {
       
        new AdminMeny(idb,anvandareID).setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnÅterställActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÅterställActionPerformed
        // TODO add your handling code here:
        txtpid.setText("");
        txtNamn.setText("");
        txtKontaktPerson.setText("");
        txtKontaktEpost.setText("");
        txtTelefon.setText("");
        txtAdress.setText("");
        txtBranch.setText("");
        txtStad.setText("");
    }//GEN-LAST:event_btnÅterställActionPerformed

    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        // TODO add your handling code here:
        try{
        String pid = txtpid.getText();
        String namn = txtNamn.getText();
        String kontaktPerson = txtKontaktPerson.getText();
        String kontaktEpost = txtKontaktEpost.getText();
        String telefon = txtTelefon.getText();
        String Adress = txtAdress.getText();
        String Branch = txtBranch.getText();
        String Stad = txtStad.getText();
        
        String Kontroll = "SELECT COUNT(*) FROM partner WHERE pid = '" + pid + "'";
        String result = idb.fetchSingle(Kontroll);
        
        if (result != null && Integer.parseInt(result) > 0) {
               JOptionPane.showMessageDialog(this, "pid existerar redan i databasen!", "Fel", JOptionPane.ERROR_MESSAGE);
           return;
                  }
       
        if (pid.isEmpty() || namn.isEmpty() || Adress.isEmpty() || telefon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fyll i alla obligatoriska fält!", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
               }
         String sql;
                sql = "INSERT INTO partner (pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad) " +
      "VALUES ('" + pid + "', '" + namn + "', '" + kontaktPerson  + "', '" + kontaktEpost + "', '" + telefon + "', '" 
      + Adress + "', '" + Branch + "', '" + Stad + "')";
         
         
            idb.insert(sql);
             JOptionPane.showMessageDialog(this, "Ny Partner lades till!");
        }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Fel vid tillägg av partner: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLäggTillActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:
         try {
        // Hämta ID från textfältet
        String pid = txtpid.getText();

        // Kontrollera att ID inte är tomt
        if (pid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vänligen ange ett giltigt pid.", "Fel", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Kontrollera om ID:t existerar i databasen
        String checkQuery = "SELECT COUNT(*) FROM partner WHERE pid = '" + pid + "'";
        String result = idb.fetchSingle(checkQuery);

        if (result == null || Integer.parseInt(result) == 0) {
            JOptionPane.showMessageDialog(this, "Ingen partner hittades med angivet pid.", "Fel", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Skapa SQL-fråga för att ta bort anställd
        String deleteQuery = "DELETE FROM partner WHERE pid = '" + pid + "'";
        System.out.println("SQL Query: " + deleteQuery); // Kontrollera frågan

        // Kör borttagningsfrågan
        idb.delete(deleteQuery);

        JOptionPane.showMessageDialog(this, "Partnern är borttagen från systemet!");

    } catch (Exception ex) {
        // Visa felmeddelande om något går fel
        JOptionPane.showMessageDialog(this, "Fel vid borttagning av Partner: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraActionPerformed
        // TODO add your handling code here:
        try {
    // Hämta värden från textfälten
    String pid = txtpid.getText();
    String namn = txtNamn.getText();
    String kontaktPerson = txtKontaktPerson.getText();
    String kontaktEpost = txtKontaktEpost.getText();
    String telefon = txtTelefon.getText();
    String adress = txtAdress.getText();
    String branch = txtBranch.getText();
    String stad = txtStad.getText();

    // Kontrollera att alla obligatoriska fält är ifyllda
    if (pid.isEmpty() || namn.isEmpty() || kontaktPerson.isEmpty() || kontaktEpost.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i alla obligatoriska fält!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kontrollera om posten med det angivna PID finns
    String checkQuery = "SELECT COUNT(*) FROM partner WHERE pid = '" + pid + "'";
    String result = idb.fetchSingle(checkQuery);

    if (result == null || Integer.parseInt(result) == 0) {
        JOptionPane.showMessageDialog(this, "Ingen partner hittades med angivet PID. Kan inte uppdatera!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Skapa UPDATE SQL-fråga
    String sql = "UPDATE partner SET "
            + "namn = '" + namn + "', "
            + "kontaktperson = '" + kontaktPerson + "', "
            + "kontaktepost = '" + kontaktEpost + "', "
            + "telefon = '" + telefon + "', "
            + "adress = '" + adress + "', "
            + "branch = '" + branch + "', "
            + "stad = '" + stad + "' "
            + "WHERE pid = '" + pid + "'";

    // Utför uppdateringen
    idb.update(sql);

    // Bekräftelsemeddelande
    JOptionPane.showMessageDialog(this, "Partnerinformationen har uppdaterats!");

} catch (Exception ex) {
    // Felhantering
    JOptionPane.showMessageDialog(this, "Fel vid uppdatering av partner: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnÄndraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ÄndraPartners().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnÄndra;
    private javax.swing.JButton btnÅterställ;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktperson;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblpid;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtKontaktEpost;
    private javax.swing.JTextField txtKontaktPerson;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtStad;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables
}
